package entity;
// Generated Nov 20, 2016 9:40:14 PM by Hibernate Tools 4.3.1


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Comments generated by hbm2java
 */
@Entity
@Table(name="COMMENTS"
    ,catalog="musicweb"
)
public class Comments  implements java.io.Serializable {


     private Integer idComment;
     private Song song;
     private Users users;
     private String content;

    public Comments() {
    }

    public Comments(Song song, Users users, String content) {
       this.song = song;
       this.users = users;
       this.content = content;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idComment", unique=true, nullable=false)
    public Integer getIdComment() {
        return this.idComment;
    }
    
    public void setIdComment(Integer idComment) {
        this.idComment = idComment;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idSong", nullable=false)
    public Song getSong() {
        return this.song;
    }
    
    public void setSong(Song song) {
        this.song = song;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idUser", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="content", nullable=false, length=1000)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }




}


