package entity;
// Generated Nov 20, 2016 9:40:14 PM by Hibernate Tools 4.3.1


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * CommentAlbum generated by hbm2java
 */
@Entity
@Table(name="COMMENT_ALBUM"
    ,catalog="musicweb"
)
public class CommentAlbum  implements java.io.Serializable {


     private Integer idCommentAlbum;
     private Album album;
     private Users users;
     private String content;

    public CommentAlbum() {
    }

    public CommentAlbum(Album album, Users users, String content) {
       this.album = album;
       this.users = users;
       this.content = content;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idCommentAlbum", unique=true, nullable=false)
    public Integer getIdCommentAlbum() {
        return this.idCommentAlbum;
    }
    
    public void setIdCommentAlbum(Integer idCommentAlbum) {
        this.idCommentAlbum = idCommentAlbum;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idAlbum", nullable=false)
    public Album getAlbum() {
        return this.album;
    }
    
    public void setAlbum(Album album) {
        this.album = album;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idUser", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="content", nullable=false, length=1000)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }




}


