package entity;
// Generated Nov 20, 2016 9:40:14 PM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name="COUNTRY"
    ,catalog="musicweb"
    , uniqueConstraints = @UniqueConstraint(columnNames="slugCountry") 
)
public class Country  implements java.io.Serializable {


     private String country;
     private String slugCountry;
     private Set<Singer> singers = new HashSet<Singer>(0);
     private Set<Category> categories = new HashSet<Category>(0);
     private Set<Playlist> playlists = new HashSet<Playlist>(0);
     private Set<Album> albums = new HashSet<Album>(0);
     private Set<Song> songs = new HashSet<Song>(0);

    public Country() {
    }

	
    public Country(String country) {
        this.country = country;
    }
    public Country(String country, String slugCountry, Set<Singer> singers, Set<Category> categories, Set<Playlist> playlists, Set<Album> albums, Set<Song> songs) {
       this.country = country;
       this.slugCountry = slugCountry;
       this.singers = singers;
       this.categories = categories;
       this.playlists = playlists;
       this.albums = albums;
       this.songs = songs;
    }
   
     @Id 

    
    @Column(name="country", unique=true, nullable=false, length=50)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    
    @Column(name="slugCountry", unique=true, length=100)
    public String getSlugCountry() {
        return this.slugCountry;
    }
    
    public void setSlugCountry(String slugCountry) {
        this.slugCountry = slugCountry;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="country")
    public Set<Singer> getSingers() {
        return this.singers;
    }
    
    public void setSingers(Set<Singer> singers) {
        this.singers = singers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="country")
    public Set<Category> getCategories() {
        return this.categories;
    }
    
    public void setCategories(Set<Category> categories) {
        this.categories = categories;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="country")
    public Set<Playlist> getPlaylists() {
        return this.playlists;
    }
    
    public void setPlaylists(Set<Playlist> playlists) {
        this.playlists = playlists;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="country")
    public Set<Album> getAlbums() {
        return this.albums;
    }
    
    public void setAlbums(Set<Album> albums) {
        this.albums = albums;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="country")
    public Set<Song> getSongs() {
        return this.songs;
    }
    
    public void setSongs(Set<Song> songs) {
        this.songs = songs;
    }




}


