package entity;
// Generated Nov 20, 2016 9:40:14 PM by Hibernate Tools 4.3.1


import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import javax.persistence.*;

/**
 * Lyric generated by hbm2java
 */
@Entity
@Table(name="LYRIC"
    ,catalog="musicweb"
)
public class Lyric  implements java.io.Serializable {


     private int idSong;
     private Song song;
     private String lyric;

    public Lyric() {
    }

	
    public Lyric(Song song) {
        this.song = song;
    }
    public Lyric(Song song, String lyric) {
       this.song = song;
       this.lyric = lyric;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="song"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="idSong", unique=true, nullable=false)
    public int getIdSong() {
        return this.idSong;
    }
    
    public void setIdSong(int idSong) {
        this.idSong = idSong;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Song getSong() {
        return this.song;
    }
    
    public void setSong(Song song) {
        this.song = song;
    }

    
    @Column(name="lyric", length=4000)
    public String getLyric() {
        return this.lyric;
    }
    
    public void setLyric(String lyric) {
        this.lyric = lyric;
    }




}


