package entity;
// Generated Nov 20, 2016 9:40:14 PM by Hibernate Tools 4.3.1


import org.hibernate.search.annotations.Field;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Singer generated by hbm2java
 */
@Entity
@Table(name="SINGER"
    ,catalog="musicweb"
    , uniqueConstraints = @UniqueConstraint(columnNames="slugSinger") 
)
public class Singer  implements java.io.Serializable {


     private Integer idSinger;
     private Category category;
     private Country country;
     private String nameSinger;
     private String keyWord;
     private String slugSinger;
     private String infoSinger;
     private String linkImgSinger;
     private Integer viewcount;
     private List<Album> albums = new ArrayList<>();
     private List<Playlist> playlists = new ArrayList<>();
     private List<Song> songs = new ArrayList<>();
     private Set<Users> userses = new HashSet<Users>(0);

    public Singer() {
    }

    public Singer(Integer idSinger, Category category, Country country, String nameSinger, String keyWord, String slugSinger, String infoSinger, String linkImgSinger, Integer viewcount, List<Album> albums, List<Playlist> playlists, List<Song> songs, Set<Users> userses) {
        this.idSinger = idSinger;
        this.category = category;
        this.country = country;
        this.nameSinger = nameSinger;
        this.keyWord = keyWord;
        this.slugSinger = slugSinger;
        this.infoSinger = infoSinger;
        this.linkImgSinger = linkImgSinger;
        this.viewcount = viewcount;
        this.albums = albums;
        this.playlists = playlists;
        this.songs = songs;
        this.userses = userses;
    }

    public Singer(String nameSinger, String linkImgSinger) {
        this.nameSinger = nameSinger;
        this.linkImgSinger = linkImgSinger;
    }
    public Singer(Category category, Country country, String nameSinger, String keyWord, String slugSinger, String infoSinger, String linkImgSinger, Integer viewcount, List<Album> albums, List<Playlist> playlists, List<Song> songs, Set<Users> userses) {
       this.category = category;
       this.country = country;
       this.nameSinger = nameSinger;
       this.keyWord = keyWord;
       this.slugSinger = slugSinger;
       this.infoSinger = infoSinger;
       this.linkImgSinger = linkImgSinger;
       this.viewcount = viewcount;
       this.albums = albums;
       this.playlists = playlists;
       this.songs = songs;
       this.userses = userses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idSinger", unique=true, nullable=false)
    public Integer getIdSinger() {
        return this.idSinger;
    }
    
    public void setIdSinger(Integer idSinger) {
        this.idSinger = idSinger;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCategory")
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="country")
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }

    @Field
    @Column(name="nameSinger", nullable=false, length=100)
    public String getNameSinger() {
        return this.nameSinger;
    }
    
    public void setNameSinger(String nameSinger) {
        this.nameSinger = nameSinger;
    }

    
   
    @Column(name="keyWord", length=100)
    public String getKeyWord() {
        return this.keyWord;
    }
    
    public void setKeyWord(String keyWord) {
        this.keyWord = keyWord;
    }

    
    @Column(name="slugSinger", unique=true, length=100)
    public String getSlugSinger() {
        return this.slugSinger;
    }
    
    public void setSlugSinger(String slugSinger) {
        this.slugSinger = slugSinger;
    }

    
    @Column(name="infoSinger", length=4000)
    public String getInfoSinger() {
        return this.infoSinger;
    }
    
    public void setInfoSinger(String infoSinger) {
        this.infoSinger = infoSinger;
    }

    
    @Column(name="linkImgSinger", nullable=false, length=500)
    public String getLinkImgSinger() {
        return this.linkImgSinger;
    }
    
    public void setLinkImgSinger(String linkImgSinger) {
        this.linkImgSinger = linkImgSinger;
    }

    
    @Column(name="viewcount")
    public Integer getViewcount() {
        return this.viewcount;
    }
    
    public void setViewcount(Integer viewcount) {
        this.viewcount = viewcount;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="singers")
    public List<Album> getAlbums() {
        return this.albums;
    }
    
    public void setAlbums(List<Album> albums) {
        this.albums = albums;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="singers")
    public List<Playlist> getPlaylists() {
        return this.playlists;
    }
    
    public void setPlaylists(List<Playlist> playlists) {
        this.playlists = playlists;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="singers")
    public List<Song> getSongs() {
        return this.songs;
    }
    
    public void setSongs(List<Song> songs) {
        this.songs = songs;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="singers")
    public Set<Users> getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }




}


